#!/usr/bin/env python3
# Rasterize the vendored Model 33 typewheel font into a Rust bitmap atlas.
#
# Run once, output checked in: normal builds and tests never execute this,
# which is why it may depend on Pillow (TTF rasterization needs freetype)
# when everything else in tools/ is stdlib-only.
#
#   python3 -m venv /tmp/fontenv && /tmp/fontenv/bin/pip install pillow
#   /tmp/fontenv/bin/python tools/mkfont703.py
#
# The atlas covers 0x20-0x5F -- the 64 glyphs on the Model 33's typewheel.
# Lowercase input is folded onto it at render time (paper::fold_to_typebox),
# the way the hardware's own code folding worked.

import argparse

FIRST_CHAR = 0x20
GLYPHS = 64

# The generated file carries its own regression test, so it must be emitted
# here rather than hand-added -- a regeneration would silently drop it.
TAIL = """
#[cfg(test)]
mod tests {
    use super::*;

    // a glyph may overhang its advance, never underrun it
    const _: () = assert!(ADVANCE <= GLYPH_W);

    /// Pins a botched regeneration: the declared geometry and the data
    /// length are emitted separately by mkfont703.py.
    #[test]
    fn the_atlas_dimensions_agree_with_its_length() {
        assert_eq!(ATLAS.len(), GLYPHS * GLYPH_W * GLYPH_H);
        // the typewheel's letter R has ink; space has none
        let g = (b'R' - FIRST_CHAR) as usize;
        assert!(ATLAS[g * GLYPH_W * GLYPH_H..(g + 1) * GLYPH_W * GLYPH_H].iter().any(|&a| a > 0));
        assert!(ATLAS[..GLYPH_W * GLYPH_H].iter().all(|&a| a == 0));
    }
}
"""

def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--font', default='fonts/TTY33MA-Book.ttf')
    ap.add_argument('--px', type=int, default=20,
                    help='raster size in pixels (default 20: a 12px advance)')
    ap.add_argument('--out', default='src/console/tty33_font.rs')
    args = ap.parse_args()

    from PIL import Image, ImageDraw, ImageFont
    font = ImageFont.truetype(args.font, args.px)
    ascent, descent = font.getmetrics()
    advances = {int(font.getlength(chr(c))) for c in range(FIRST_CHAR, FIRST_CHAR + GLYPHS)}
    assert len(advances) == 1, f'not monospaced: {advances}'
    advance = advances.pop()
    glyph_h = ascent + descent

    # Find the widest rendered glyph: a face may overhang its advance by a
    # pixel or two, and clipping it would shave serifs. The cell is that
    # wide; the renderer still steps by the advance.
    cells = []
    glyph_w = advance
    for c in range(FIRST_CHAR, FIRST_CHAR + GLYPHS):
        img = Image.new('L', (advance * 2, glyph_h), 0)
        # anchor 'la': x is the pen position, y the ascender line, so every
        # glyph lands on the same baseline
        ImageDraw.Draw(img).text((0, 0), chr(c), font=font, fill=255, anchor='la')
        bb = img.getbbox()
        if bb:
            glyph_w = max(glyph_w, bb[2])
        cells.append(img)

    atlas = bytearray()
    for img in cells:
        for y in range(glyph_h):
            for x in range(glyph_w):
                atlas.append(img.getpixel((x, y)))

    with open(args.out, 'w') as f:
        f.write(f'''// vim: ts=4:sw=4:expandtab:
/*
 * Copyright (c) 2026 Travis Geiselbrecht
 *
 * Use of this source code is governed by a MIT-style
 * license that can be found in the LICENSE file or at
 * https://opensource.org/licenses/MIT
 */
//! The Model 33 typewheel as a bitmap atlas, for the teletype window.
//!
//! Generated by `tools/mkfont703.py` -- do not edit. The pixel data is a
//! rasterization of `fonts/TTY33MA-Book.ttf` (teletypewriter-fonts
//! project), licensed under the SIL Open Font License 1.1; see
//! `fonts/OFL.txt` and `fonts/README.md` for provenance.
//!
//! 8-bit alpha, glyph-major: glyph `g` (char `0x20 + g`), row `y`, column
//! `x` is `ATLAS[(g * GLYPH_H + y) * GLYPH_W + x]`. Glyphs share a
//! baseline; a glyph may overhang [`ADVANCE`], which is the carriage step.

/// First codepoint in the atlas (space); coverage runs 64 glyphs to 0x5F.
pub const FIRST_CHAR: u8 = {FIRST_CHAR:#04x};
pub const GLYPHS: usize = {GLYPHS};
/// Cell size in pixels (the cell is as wide as the widest glyph).
pub const GLYPH_W: usize = {glyph_w};
pub const GLYPH_H: usize = {glyph_h};
/// Horizontal pen step per character -- the typewheel's fixed pitch.
pub const ADVANCE: usize = {advance};

#[rustfmt::skip]
pub static ATLAS: [u8; GLYPHS * GLYPH_W * GLYPH_H] = [
''')
        for i in range(0, len(atlas), 16):
            f.write('    ' + ' '.join(f'{b:#04x},' for b in atlas[i:i+16]) + '\n')
        f.write('];\n')
        f.write(TAIL)
    print(f'{args.out}: {GLYPHS} glyphs, cell {glyph_w}x{glyph_h}, advance {advance}, '
          f'{len(atlas)} bytes')

if __name__ == '__main__':
    main()
